import { Shield } from "lucide-react";
import { Link } from "wouter";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="flex items-center justify-between mb-12">
          <div className="flex items-center gap-2">
            <Shield className="w-6 h-6 text-blue-500" />
            <span className="text-lg font-semibold tracking-tight">Sentri</span>
          </div>
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">← Back to Sentri</Link>
        </div>

        {/* Title */}
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 2026</p>

        {/* Section 1 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Acceptance of Terms</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          By accessing or using Sentri, you agree to be bound by these Terms of Service and our
          Privacy Policy. If you do not agree to these terms, you may not use the service. These
          terms apply to all users, including individuals using Sentri on behalf of an organisation.
          Continued use of the service following any updates to these terms constitutes your
          acceptance of the revised terms.
        </p>

        {/* Section 2 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Description of Service</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Sentri is an AI-powered IT incident triage tool that helps teams manage, prioritise, and
          track support tickets. The AI analysis features are intended to assist human decision-making,
          not replace it. We do not guarantee the resolution of any IT incident, and triage
          recommendations generated by Sentri's AI should be reviewed by a qualified IT professional
          before action is taken. Sentri reserves the right to modify, suspend, or discontinue any
          part of the service at any time with reasonable notice.
        </p>

        {/* Section 3 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">User Responsibilities</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          You are responsible for the content you submit through Sentri. Avoid including sensitive
          credentials such as passwords, private certificates, or confidential financial data in
          ticket descriptions. Ticket content is processed by third-party AI services — use good
          judgment about what you include. You are also responsible for maintaining the security of
          your account credentials and for any activity that occurs under your account.
        </p>

        {/* Section 4 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Acceptable Use</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          You agree not to misuse the Sentri platform. Prohibited activities include, but are not
          limited to:
        </p>
        <ul className="text-muted-foreground text-sm leading-relaxed list-disc list-inside mt-2 space-y-1">
          <li>Scraping, crawling, or programmatically harvesting data from the platform without authorisation.</li>
          <li>Abusing the AI analysis endpoint through excessive automated requests or intentional prompt injection.</li>
          <li>Submitting illegal, harmful, or offensive content through ticket fields.</li>
          <li>Attempting to circumvent authentication, access controls, or rate limits.</li>
          <li>Using Sentri to facilitate any activity that violates applicable laws or regulations.</li>
        </ul>
        <p className="text-muted-foreground text-sm leading-relaxed mt-3">
          We reserve the right to suspend or terminate accounts that violate these policies without
          prior notice.
        </p>

        {/* Section 5 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Intellectual Property</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Sentri, including its AI models, interface, branding, and underlying software, is the
          intellectual property of Sentri and its licensors. Nothing in these terms grants you
          ownership of or a licence to our IP beyond what is necessary to use the service. Your
          ticket data — the incidents, descriptions, and notes you create — remains yours. We do not
          claim ownership over your content and will not use it for purposes beyond providing and
          improving the service as described in our Privacy Policy.
        </p>

        {/* Section 6 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Limitation of Liability</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Sentri is provided "as is" without warranties of any kind, express or implied. We do not
          warrant that the service will be uninterrupted, error-free, or that AI triage output will
          be accurate or complete. To the fullest extent permitted by law, Sentri and its team shall
          not be liable for any indirect, incidental, consequential, or special damages arising from
          your use of the service, including but not limited to IT decisions made in reliance on
          AI-generated recommendations. Your use of Sentri's AI analysis features is entirely at
          your own discretion and risk.
        </p>

        {/* Section 7 */}
        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3">Contact</h2>
        <p className="text-muted-foreground text-sm leading-relaxed">
          If you have questions about these Terms of Service, please contact us at{" "}
          <a
            href="mailto:legal@sentri.ai"
            className="text-violet-400 hover:text-violet-300 transition-colors"
          >
            legal@sentri.ai
          </a>
          .
        </p>
      </div>
    </div>
  );
}
